server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 10
  shutdown: graceful

spring:
  application:
    name: config-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  cloud:
    config:
      server:
        git:
          uri: https://github.com/alexandresb/config-repo
          default-label: master
          #propriété de configuration permettant une meilleure résilience
          timeout: 5 #temps max pour établir la connexion avec le dépôt distant
          clone-on-start: true #copie au démarrage en local du dépôt de config distant
          force-pull: true # récupération d'une copie "neuve" quand le dépôt local est corrompu

info:
  system: Polar Bookshop

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, info, heapdump
  endpoint:
    health:
      show-details: always
      show-components: always
      #activation des EP /actuator/health/liveness et readiness
      probes:
        enabled: true
  #tag des métriques exposées avec une clé/valeur application=nom app
  metrics:
    tags:
      applications: ${spring.application.name}
  info:
    env:
      enabled: true
    os:
      enabled: true
    java:
      enabled: true

#customisation des infos de logging : ajout d'infos après le log level (%5p)
logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"